### PR TITLE
Updated SQLDumper.php

### PR DESCRIPTION
**Pull request by mbsaberi**
I've used your library and it worked well. Just it needs to be compatible with UTF-8 encoding. I have added this feature at the line 76.
I hope it can be a useful update on your package.

### CODE REVIEW

**Comment by Y0lk** [comment]
Probably a good idea to add that, but you added a new file at the root, instead of modifying the file in src/SQLDumper.php

**Comment by mbsaberi** [comment]
> Probably a good idea to add that, but you added a new file at the root, instead of modifying the file in src/SQLDumper.php

You are right. It was my mistake.
If you want I will add the file to the correct path, otherwise you may do it.
Acutually it is my first contribute on a project in Github. Sorry for the mistake.
To inform you, I have tested the applied edit and it worked well.

**Comment by Y0lk** [comment]
This is old but you never updated your pull request so I'm closing this now. I've fixed this issue now

**Comment by mbsaberi** [comment]
@Y0lk Thank you for your fixation. I forgot about updating this issue and pull request.

**Pull request closed without merging**
